export enum CommunityGovernanceSteps {
    BASIC = 'BASIC',
    AUTHORITY = 'AUTHORITY',
    PROTOCOLS = 'PROTOCOLS',
    REVIEW = 'REVIEW'
}
export enum CommunityGovernance {
  INDIGENOUS_COUNCIL = 'INDIGENOUS_COUNCIL',
  ELDER_COUNCIL = 'ELDER_COUNCIL',
  STEWARDSHIP_CIRCLE = 'STEWARDSHIP_CIRCLE'
}

export enum TKLabel {
  SECRET_SACRED = 'SECRET_SACRED',
  CULTURAL_INFLUENCE = 'CULTURAL_INFLUENCE',
  WOMEN_S_ONLY = 'WOMEN_S_ONLY',
  MEN_S_ONLY = 'MEN_S_ONLY'
}

export enum CulturalProtocol {
  PUBLIC = 'PUBLIC',
  COMMUNITY_ONLY = 'COMMUNITY_ONLY',
  ELDER_APPROVAL_REQUIRED = 'ELDER_APPROVAL_REQUIRED',
  GENDER_RESTRICTED = 'GENDER_RESTRICTED'
}

export enum LicensingOption {
  ATTRIBUTION = 'ATTRIBUTION',
  ATTRIBUTION_SHARE_ALIKE = 'ATTRIBUTION_SHARE_ALIKE',
  ATTRIBUTION_NON_COMMERCIAL = 'ATTRIBUTION_NON_COMMERCIAL',
  COMMUNITY_PROTOCOL = 'COMMUNITY_PROTOCOL',
  ALL_RIGHTS_RESERVED = 'ALL_RIGHTS_RESERVED'
}

  export const steps = [
    CommunityGovernanceSteps.BASIC,
    CommunityGovernanceSteps.AUTHORITY,
    CommunityGovernanceSteps.PROTOCOLS,
    CommunityGovernanceSteps.REVIEW
  ];


export enum CollectionType {
  EVENTS = 'EVENTS',
  CULTURAL_PRACTICE = 'CULTURAL_PRACTICE',
  RITUAL = 'RITUAL',
  ORAL_HISTORY = 'ORAL_HISTORY',
  TRADITIONAL_KNOWLEDGE = 'TRADITIONAL_KNOWLEDGE',
  ARTIFACTS = 'ARTIFACTS',
  CEREMONIES = 'CEREMONIES'
}
