import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'

import './globals.css'
import { Inter } from 'next/font/google'
import { Main } from 'next/document'
import MainFooter from './components/layout/footer'
import Navigation from './utils/nav/navigation'
const inter = Inter({ subsets: ['latin'] })
import "leaflet/dist/leaflet.css"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          {/* <Navigation /> */}
          {children}
          {/* <MainFooter /> */}
        </body>
      </html>
    </ClerkProvider>
  )
}
