import type { Metadata } from 'next'

import '@/app/globals.css'
import { Inter } from 'next/font/google'

import MainFooter from '../components/layout/footer'
import Navigation from '../utils/nav/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function PublicResourcesLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Navigation />
        {children}
        <MainFooter />
      </body>
    </html>
  )
}
